apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: chatapp
spec:
  capacity:
    storage: 2Gi
  # volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath: 
    path: /data/mongo
